version: "3.8"

networks:
  mimir-net:
    external: true

services:
  ftt-alloy:
    image: grafana/alloy:latest
    container_name: ftt-alloy
    command:
      - run
      - --stability.level=experimental   # GA 이하 컴포넌트 허용
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy
      - /etc/alloy/config.alloy
    environment:
      - AWS_REGION=ap-southeast-1        # S3 / CW 공통 리전
    ports:
      - "12345:12345"          # ← 호스트 포트 매핑 추가
    volumes:
      - ./config/config.alloy:/etc/alloy/config.alloy:ro
      - ./alloy-data:/var/lib/alloy
    restart: unless-stopped
    networks:
      - mimir-net

volumes:
  alloy-data:

~                               